config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout"  => "sessions#destroy"

  resources :users, except: :destroy do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :index do
    resources :lessons
  end
  resources :words

  namespace :admin do
    resources :categories
    resources :users
    resources :words
    resources :imports
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.order_by.paginate page: params[:page]
    end
  end

  def about
  end
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
    </aside>
    <div class="col-md-8">
      <div class="form-group">
        <div class="col-lg-10 center">
          <% if !admin_check? %>
            <%= link_to t("admin_category"), categories_path , class: "btn btn-lg btn-primary" %>
            <%= link_to t("word_list"), words_path , class: "btn btn-lg btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <h3><%= t "activity_name" %></h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1><%= t "title" %></h1>
  <h2><%= t "homepage_content" %></h2>
  <%= link_to t("sign_up_btn"), signup_path , class: "btn btn-lg btn-primary" %>
</div>
<% end %>