config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout"  => "sessions#destroy"

  resources :users, except: :destroy do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :index do
    resources :lessons
  end
  resources :words

  namespace :admin do
    resources :categories
    resources :users
    resources :words
    resources :imports
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  require "csv"
  belongs_to :category
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
  validates :content, presence: true

  scope :order_by,-> {order created_at: :DESC}
  scope :learn, ->user, category{where "id in (select word_id from results where
    lesson_id in (select id from lessons where user_id = #{user.id})) AND category_id = #{category.id}"}

  scope :not_learn, ->user, category{where "id not in (select word_id from results where
    lesson_id in (select id from lessons where user_id = #{user.id})) AND category_id = #{category.id}"}

  class << self
    def import file
      CSV.foreach(file.path, headers: true) do |row|
        word_hash = row.to_hash
        word=Word.where(content: word_hash["content_word"])
        if word.count == 0
          user=Word.create! content: word_hash["content_word"], category_id: word_hash["category_id"]
          if !user.nil?
            Answer.create! content: word_hash["content_answer1"], correct: word_hash["correct1"], word_id: user.id
            Answer.create! content: word_hash["content_answer2"], correct: word_hash["correct2"], word_id: user.id
            Answer.create! content: word_hash["content_answer3"], correct: word_hash["correct3"], word_id: user.id
            Answer.create! content: word_hash["content_answer4"], correct: word_hash["correct4"], word_id: user.id
          end
        end
      end
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :load_categories
  before_action :load_word, only: [:destroy, :edit, :update]

  def index
    @words=Word.order_by.paginate page: params[:page]
  end

  def edit
  end

  def new
    @word = Word.new
    Settings.number_answer.times do
      @answer = @word.answers.build
    end
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t "create_succesfull"
      redirect_to admin_words_path
    else
      render :edit
    end
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "update_succesfull"
      redirect_to admin_words_path
    else
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t "delete"
      redirect_to admin_words_path
    end
  end

  private

  def word_params
    params.require(:word).permit :content, :category_id, answers_attributes: [:id,
      :content, :correct]
  end

  def load_word
    @word = Word.find params[:id]
  end

  def load_categories
    @categories = Category.all
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = nil
    @categories = Category.all
    if params[:category_id]
      @category = Category.find params[:category_id]
      case params[:condition]
      when Settings.word_learned
        @words = Word.learn current_user, @category
      when Settings.word_notlearned
        @words = Word.not_learn current_user, @category
      when Settings.word_all
        @words = @category.words
      end
    end
  end
end

app/views/admin/words/_answer_form.html.erb
<div class="row answer-form">
  <div class="col-md-5 ">
    <%= f.label :answer %>
    <%= f.text_field :content, class: "form-control content-answer" %>
    </div>
  <div class="col-md-3">
    <%= f.label :correct, class: "checkbox-inline" %>
    <%= f.check_box :correct, class: "checkbox" %>
  </div>
</div>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :word %>
  <%= f.text_field :content, class: "form-control"%>

  <div class="form-group">
    <h4><%= t "admin_category" %></h4>
    <%= f.select :category_id, options_from_collection_for_select(@categories, "id",
      "name", params[:category_id]), class: "form-control" %>
  </div>
  <div id="answers">
    <%= f.fields_for :answers do |answer_form| %>
      <%= render "answer_form", f: answer_form  %>
    <% end %>
  </div>

  <%= f.submit t("save"), class: " submit-word btn btn-primary pull-right" %>
<% end %>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.id %></td>
  <td><%= word.content %></td>
  <td>
    <% word.answers.each do |answer| %>
      <%= answer.content if answer.correct %>
    <% end %>
  </td>
  <td>
    <%= link_to t("categories_btn_edit"), edit_admin_word_path(word), class: "btn btn-primary" %>
    <%= link_to t("categories_btn_delete"), admin_word_path(word), class: "btn btn-primary",
      method: :delete, data: {confirm: t("you_sure")} %>
  </td>
</tr>

app/views/admin/words/edit.html.erb
<% provide :title, t("word") %>
<h1><%= t "updated_word" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-2 ">
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t("word") %>
<h1><%= t "word_list" %></h1>
<div class="row">
  <%= link_to t("categories_new"), new_admin_word_path , class: "btn btn-success button" %>
</div>
<br>
<% if @words %>
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th><%= t "id" %></th>
        <th><%= t "word" %></th>
        <th><%= t "answer" %></th>
        <th><%= t "status" %></th>
      </tr>
    </thead>
    <tbody id="words">
      <%= render @words %>
    </tbody>
  </table>
  <%= will_paginate %>
<% end %>
<div class="row">
<h3><%= t "import_csv_title" %></h3>
  <%= form_tag admin_imports_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag t("import_csv") %>
  <% end %>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t("word") %>
<h1><%= t "create_new_word" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3 ">
   <%= render "form" %>
  </div>
</div>