config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout"  => "sessions#destroy"

  resources :users, except: :destroy do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :index do
    resources :lessons
  end
  resources :words

  namespace :admin do
    resources :categories
    resources :users
    resources :words
    resources :imports
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form_error" %><%= pluralize object.errors.count, t("error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="activities">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_relationship_path(@user, relationship: "following") %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "following" %>
  </a>
  <a href="<%= user_relationship_path(@user, relationship: "followers") %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(@user ||= current_user), @user %>
<h1><%= @user.name %></h1>