config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout"  => "sessions#destroy"

  resources :users, except: :destroy do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :index do
    resources :lessons
  end
  resources :words

  namespace :admin do
    resources :categories
    resources :users
    resources :words
    resources :imports
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 50}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :load_category, except: [:index, :new, :create]

  def new
    @categories = Category.new
  end

  def create
    @categories = Category.new category_params
    if @categories.save
      flash[:success] = t "title"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def index
    @categories = Category.all
  end

  def edit
  end

  def update
    if @categories.update_attributes category_params
      flash[:success] = t "update_succesfull"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @categories.destroy
    flash[:success] = t "delete"
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @categories = Category.find params[:id]
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.created_at.strftime t("time") %></td>
  <td><%= category.name %></td>
  <td><%= category.description %></td>
  <td>
    <%= link_to t("lesson_start"), category_lessons_path(category_id: category.id),
    method: :post, class: "btn btn-primary btn-xs" %>
    <%= link_to t("categories_btn_edit"), edit_admin_category_path(category), class: "btn btn-primary btn-xs" %>
    <%= link_to t("categories_btn_delete"), admin_category_path(category), class: "btn btn-primary btn-xs",
      method: :delete, data: {confirm: t("you_sure")} %>
  </td>
</tr>

app/views/admin/categories/edit.html.erb
<% provide :title, t("categories") %>
<h1><%= t "categories_updates" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @categories] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit t("categories_save") , class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t("categories") %>
<h1><%= t "categories" %></h1>
<div id="wrapper">
  <div class="content container">
    <div class="row exam">
      <div class="col-md-10 col-md-offset-1">
        <div>
          <h3><%= t "categories_list" %></h3>
          <%= link_to t("categories_new"), new_admin_category_path , class: "btn btn-success button" %>
        </div>
        <br>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th class="created_date"><%= t "categories_create" %></th>
              <th class="name"><%= t "categories_name" %></th>
              <th class="des"><%= t "categories_des" %></th>
              <th class=""></th>
            </tr>
          </thead>
          <tbody>
             <%= render @categories %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t("categories") %>
<h1><%= t "categories_title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @categories] do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.submit t("categories_title") , class: "btn btn-primary" %>
    <% end %>
  </div>
</div>